### ISSUE TITLE
Add explicit runtime dependency on faraday itself

### ISSUE THREAD

**Issue by olbrich** [lostisland/faraday-net_http#25]
https://github.com/lostisland/faraday-net_http/blob/1b926b2d4919a2a6ed8c50eef08943b9f346b329/faraday-net_http.gemspec#L27

The gemspec declares faraday as a development dependency, but not a runtime one. Effectively this will allow this gem to be installed with any version of Faraday, even pre-1.0 versions.

Normally this won't cause problems, but if this gem appears earlier in your Gemfile than Faraday itself or another dependency that relies on Faraday, then you can get errors because the call to `register_middleware` in https://github.com/lostisland/faraday-net_http/blob/1b926b2d4919a2a6ed8c50eef08943b9f346b329/lib/faraday/net_http.rb#L8 will fail and you can get errors like...

```
NoMethodError:
  undefined method `register_middleware' for Faraday::Adapter:Class

      Faraday::Adapter.register_middleware(net_http: Faraday::Adapter::NetHttp)
```

**Comment by iMacTia** [comment]
Hi @olbrich, we do this because `net_http` is the default adapter and is included in [Faraday's gemspec](https://github.com/lostisland/faraday/blob/main/faraday.gemspec#L18).
If we were to make it a runtime dependency, it would cause a circular dependency and `bundler` would raise an error.

You're not supposed to add this gem directly in your Gemfile or require it in your project.
Think of it as a "bundled gem" that comes with Faraday 😄

I hope this clarifies but please do let me know if you have any follow-up question

**Comment by olbrich** [comment]
Ah, that makes sense. I ran into this because I included 'faraday-net_http_persistent' in my bundle. It depends on `faraday-net_http`, but not `faraday` itself.
